Development
shraazp/flipkart-clone pull request #1
Opened 2022-01-31 02:48 UTC by shraazp

2022-02-01 11:12 UTC, CandleCoder commented
**Hi Providing you the Generic Points here while file by file review comments will be provided with github review - ** 

- Rename - FooterC Component used in your code as the class name differs with file name.
- Rewrite / Change the app with typescript (Breaking changes may happen but as per the discussion with sourav we will use typescript)
- Each Class is Required with comments What it is doing and what is its significance!
- Remove Commented code - I know the fact that this is still under development code!
- Try to wrap each component with <div></div> for better DOM Management!
- Follow the camel casing properly e.g in Component  - Dropdown.jsx , upArrow is written fine but dropdown is not looking good and so on.
- In Component About the styles are not segregated!
- In header folder each components needed to have a separated scss files!
- In Slide component src = "" can be imported to some const and can be used at multiple places in the code!
- In Slide component if alt =  "" not required kindly remove it!
- In Component Categories React.useState(fashion["Mens's Top Wear"]) the String value can be placed in some constant and likewise for other constants which will be same!
- For constants you can segregated these constants with different work like for events different constants , values different and so on!!

2022-02-01 11:17 UTC, CandleCoder commented on src/components/ImageSlider/Slide.jsx
> +          <img className="carousel-image" src="https://rukminim1.flixcart.com/flap/1688/280/image/30a361b00075c80e.jpg?q=50" alt="" />
Try to assign a constants to these image src!

2022-02-01 11:25 UTC, CandleCoder requested changes
Kindly see above comments and resolve them.

2022-02-01 11:25 UTC, CandleCoder commented on src/components/dialog/Login.jsx
> +// import DialogActions from '@mui/material/DialogActions';
If not needed in future kindly remove all commented codes

2022-02-01 11:25 UTC, CandleCoder commented on src/components/ImageSlider/Slide.jsx
> +          <img className="carousel-image" src="https://rukminim1.flixcart.com/flap/1688/280/image/30a361b00075c80e.jpg?q=50" alt="" />
ry to assign a constants to these image src!

2022-02-01 11:25 UTC, CandleCoder commented on src/components/dialog/Login.scss
> +    max-width: unset !important
Try to avoid important overrides unless highly required

2022-02-01 11:25 UTC, CandleCoder commented on src/components/footer/About.jsx
> +            color: '#878787', fontSize: 12, fontWeight: 400, marginBottom: 9,
Try to use the Styles Via Constants

2022-02-01 11:25 UTC, CandleCoder commented on src/components/header/Drawer.jsx
> +    display: 'flex',
Try to segregate style items if possible.

2022-02-01 11:25 UTC, CandleCoder commented on src/components/navbar/Categories.jsx
> +  const [category, setCategory] = React.useState(fashion["Mens's Top Wear"]);
Use initial state values from constants or any generators (if any)

2022-02-01 11:25 UTC, CandleCoder commented on src/components/navbar/categories.scss
> +// .container:hover .categories-link{
Remove unused css codes - can be ignored if it is required in future.

2022-02-01 11:25 UTC, CandleCoder commented on src/reportWebVitals.js
> -
You must have included this file as this will help you for the performance things and logging in the future for better debugging.

2022-02-07 03:02 UTC, shraazp commented
All the said changes have been implemented in the code.

2022-02-10 04:30 UTC, merged